<a href="https://colab.research.google.com/github/SP-TechForest/Python-creations/blob/main/Machine_Learning_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import sklearn
import plotly.express as px 
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [69]:
data = pd.read_csv("Social_Network_Ads.csv")
data.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [70]:
data.shape

(400, 3)

In [71]:
data.Purchased.value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [72]:
age_prob = data.groupby(["Age"])["Purchased"].sum()

In [73]:
px.bar(x = age_prob.axes[0], y = age_prob.values)

In [74]:
feature = data.iloc[:,:-1].values
target = data.iloc[:,-1].values
x_train,x_test, y_train, y_test = train_test_split(feature,target,
                                                   test_size=0.2, random_state = 0)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((320, 2), (80, 2), (320,), (80,))

In [75]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)


#Logistic Regression 


In [76]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state=0)

In [77]:
lr.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [78]:
y_pred = lr.predict(x_test)

In [79]:
sklearn.metrics.r2_score(y_test, y_pred)

0.4357366771159875

In [80]:
x_test[0]

array([-0.49618606,  0.56021375])

In [81]:
lr.predict(sc.transform([[30,87000]]))

array([0])

In [82]:
y_test[0]

0

In [83]:
np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0,

In [84]:
sklearn.metrics.confusion_matrix(y_test, y_pred)

array([[52,  6],
       [ 3, 19]])

In [85]:
sklearn.metrics.accuracy_score(y_test, y_pred)

0.8875

#K-NN (Classification)

In [86]:
data.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [87]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors= 5, metric="minkowski", p = 2)
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [88]:
y_pred = knn.predict(x_test)

In [89]:
sklearn.metrics.confusion_matrix(y_test, y_pred)

array([[54,  4],
       [ 1, 21]])

In [90]:
sklearn.metrics.accuracy_score(y_test, y_pred)

0.9375

#Support Vector Machine 

In [91]:
from sklearn.svm import SVC
svc = SVC(kernel="linear")

In [92]:
svc.fit(x_train, y_train)

SVC(kernel='linear')

In [93]:
y_pred = svc.predict(x_test)

In [94]:
np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0,

In [95]:
sklearn.metrics.confusion_matrix(y_test, y_pred)

array([[52,  6],
       [ 3, 19]])

In [96]:
sklearn.metrics.accuracy_score(y_test, y_pred)

0.8875

In [97]:
svc_rbf = SVC(kernel="rbf")

In [98]:
svc_rbf.fit(x_train, y_train)

SVC()

In [99]:
y_pred2 = svc_rbf.predict(x_test)
sklearn.metrics.accuracy_score(y_test, y_pred2)

0.9375

In [100]:
sklearn.metrics.confusion_matrix(y_test, y_pred2)

array([[54,  4],
       [ 1, 21]])

#Naive Bayes<br>
<ul><li>All the feature must be independent</li></ul>

In [101]:
px.scatter(data,x = data.Age, y = data.EstimatedSalary, color = "Purchased",
           color_discrete_sequence=px.colors.qualitative.Set1)

In [102]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(x_train, y_train)

GaussianNB()

In [103]:
y_pred = nb.predict(x_test)

In [104]:
sklearn.metrics.confusion_matrix(y_test, nb.predict(x_test))

array([[54,  4],
       [ 1, 21]])

In [105]:
sklearn.metrics.accuracy_score(y_test, nb.predict(x_test))

0.9375


#@