<a href="https://colab.research.google.com/github/SP-TechForest/Python-creations/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import pandas

In [3]:
print(tf.__version__)

2.7.0


In [4]:
scalar = tf.constant(7)

In [5]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
scalar.ndim

0

In [9]:
vector = tf.constant([10,20])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [10]:
vector.ndim

1

In [12]:
matrix = tf.constant([[1,2]
                      ,[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [13]:
matrix.ndim

2

In [18]:
matrix2 = tf.constant([[1,2,3],[4,5,6],[6,7,8]], dtype = tf.float16)

In [19]:
matrix2

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [6., 7., 8.]], dtype=float16)>

In [25]:
tensor = tf.constant([[[1,2,3,4],
                      [5,6,7,8]],
                     [[1,2,3,4],
                      [1,2,3,4]],
                     [[1,2,3,4],
                      [1,2,3,4]]])
tensor

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]]], dtype=int32)>

In [26]:
tensor.ndim

3

In [28]:
tensor2  = tf.constant([[[1,2,3,4]],[[1,2,3,4]]])
tensor2

<tf.Tensor: shape=(2, 1, 4), dtype=int32, numpy=
array([[[1, 2, 3, 4]],

       [[1, 2, 3, 4]]], dtype=int32)>

In [34]:
t1 = tf.Variable(20)

In [37]:
changable_tensor = tf.Variable([10,10])
unchangable_tensor = tf.constant([10,10])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [43]:
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>

use assign to change value 

In [47]:
changable_tensor2 = tf.Variable([[[1,2,3,4],
                      [5,6,7,8]],
                     [[1,2,3,4],
                      [1,2,3,4]],
                     [[1,2,3,4],
                      [1,2,3,4]]])
changable_tensor2

<tf.Variable 'Variable:0' shape=(3, 2, 4) dtype=int32, numpy=
array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]]], dtype=int32)>

## Create random tensors