<a href="https://colab.research.google.com/github/SP-TechForest/Python-creations/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import pandas

In [ ]:
print(tf.__version__)

2.7.0


In [ ]:
scalar = tf.constant(7)

# Use of COnstant and Variable to make tensors<hr>

In [ ]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10,20])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[1,2]
                      ,[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
matrix2 = tf.constant([[1,2,3],[4,5,6],[6,7,8]], dtype = tf.float16)

In [ ]:
matrix2

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [6., 7., 8.]], dtype=float16)>

In [ ]:
tensor = tf.constant([[[1,2,3,4],
                      [5,6,7,8]],
                     [[1,2,3,4],
                      [1,2,3,4]],
                     [[1,2,3,4],
                      [1,2,3,4]]])
tensor

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
tensor2  = tf.constant([[[1,2,3,4]],[[1,2,3,4]]])
tensor2

<tf.Tensor: shape=(2, 1, 4), dtype=int32, numpy=
array([[[1, 2, 3, 4]],

       [[1, 2, 3, 4]]], dtype=int32)>

In [ ]:
t1 = tf.Variable(20)

In [ ]:
changable_tensor = tf.Variable([10,10])
unchangable_tensor = tf.constant([10,10])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [ ]:
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>

use assign to change value 

In [ ]:
changable_tensor2 = tf.Variable([[[1,2,3,4],
                      [5,6,7,8]],
                     [[1,2,3,4],
                      [1,2,3,4]],
                     [[1,2,3,4],
                      [1,2,3,4]]])
changable_tensor2

<tf.Variable 'Variable:0' shape=(3, 2, 4) dtype=int32, numpy=
array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]]], dtype=int32)>

Constant creates unchangable tensros. <br>
Variable generates changable tensors. 

## Create random tensors<hr>

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
tf.random.set_seed(111)
tf.random.uniform([1,5,6])

<tf.Tensor: shape=(1, 5, 6), dtype=float32, numpy=
array([[[0.22793007, 0.07242179, 0.25905025, 0.26928675, 0.99596477,
         0.21952057],
        [0.19156086, 0.7613294 , 0.89160967, 0.22138035, 0.1934278 ,
         0.6977569 ],
        [0.5775132 , 0.6305827 , 0.5463754 , 0.7712686 , 0.6112319 ,
         0.00575221],
        [0.6060922 , 0.1935494 , 0.74294245, 0.980145  , 0.13235426,
         0.6069268 ],
        [0.35117865, 0.8777567 , 0.12334549, 0.2773801 , 0.517432  ,
         0.04045439]]], dtype=float32)>

In [ ]:
tf.random.uniform([1,5,6])

<tf.Tensor: shape=(1, 5, 6), dtype=float32, numpy=
array([[[0.86369586, 0.60063684, 0.95674896, 0.7128948 , 0.50341344,
         0.9982449 ],
        [0.56112504, 0.37694383, 0.83077204, 0.01545227, 0.33032954,
         0.6329814 ],
        [0.7801497 , 0.8009933 , 0.9957398 , 0.5391377 , 0.45974958,
         0.23468137],
        [0.51416945, 0.9229262 , 0.52210605, 0.1595906 , 0.02170455,
         0.97483253],
        [0.13269508, 0.68724465, 0.74411213, 0.46654022, 0.607587  ,
         0.32690895]]], dtype=float32)>

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3, 2)) # create tensor from a normal distribution 
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
tf.random.set_seed(4)
a = tf.random.shuffle([1,2,3,4,5,6], seed=567436).numpy()
tf.random.set_seed(4)
b = tf.random.shuffle([1,2,3,4,5,6], seed=567436).numpy()
a,b

(array([1, 4, 2, 3, 5, 6], dtype=int32),
 array([1, 4, 2, 3, 5, 6], dtype=int32))

If we use seed then we will get same random out put, But the seed value should be same, if seed value is different then your values will be different.<br>
you must have to assign seed value before each operation. 





# Norrmal Vs. Uniform<hr>
tf.random.normal() -> Make Normal distribution of data points (not eaqualy)<br>

tf.random.uniform -> Make Uniform distribution of data points (quality)


In [ ]:
tf.random.uniform([5]).ndim

1

In [ ]:
tf.random.normal(shape = ([3,5])).ndim

2

In [ ]:
random_uniform = tf.random.uniform([3,2])

In [ ]:
random_uniform

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.546034  , 0.7847378 ],
       [0.04293239, 0.5031413 ],
       [0.49900854, 0.1146431 ]], dtype=float32)>

# Shuffeled the tensors with seed.<hr> 
<br> If you use seed then it will give you same out put. otherwise, it will give you different out put every time. 



  

In [ ]:
tf.random.shuffle(random_uniform)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.546034  , 0.7847378 ],
       [0.49900854, 0.1146431 ],
       [0.04293239, 0.5031413 ]], dtype=float32)>

In [ ]:
tf.random.set_seed(11)
tf.random.shuffle(random_uniform, seed=22)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.49900854, 0.1146431 ],
       [0.04293239, 0.5031413 ],
       [0.546034  , 0.7847378 ]], dtype=float32)>

In [ ]:
tf.random.set_seed(11)
tf.random.shuffle(random_uniform, seed=22)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.49900854, 0.1146431 ],
       [0.04293239, 0.5031413 ],
       [0.546034  , 0.7847378 ]], dtype=float32)>

# Another Ways to create tensors <hr>

In [ ]:
tf.ones([5,5])

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([5,5])

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
import numpy as np
numpy_1 = np.arange(1,50,2)
numpy_1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [ ]:
tf.constant(numpy_1)

<tf.Tensor: shape=(25,), dtype=int64, numpy=
array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])>

In [ ]:
tf.Variable(numpy_1)[5].assign(22)

<tf.Variable 'UnreadVariable' shape=(25,) dtype=int64, numpy=
array([ 1,  3,  5,  7,  9, 22, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])>

In [ ]:
tf_n = tf.constant(numpy_1, shape = (5,5))
tf_n

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])>

In [ ]:
tf2 = tf.Variable(numpy_1)
tf2

<tf.Variable 'Variable:0' shape=(25,) dtype=int64, numpy=
array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])>

In [ ]:
tf.reshape(tf2, [5,5]).ndim

2

In [ ]:
tf.Variable(numpy_1)

<tf.Variable 'Variable:0' shape=(25,) dtype=int64, numpy=
array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])>

In [ ]:
tf.random.set_seed(42)
a = tf.random.uniform(shape = (5,5))
tf.random.set_seed(42)
b = tf.random.uniform(shape = (5,5))
a,b

(<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041],
        [0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686],
        [0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ],
        [0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ],
        [0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ]],
       dtype=float32)>, <tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041],
        [0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686],
        [0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ],
        [0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ],
        [0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ]],
       dtype=float32)>)

In [ ]:
tf3 = tf.constant(np.arange(1,51), shape = (5,5,2))
tf.random.set_seed(44)
tf.random.shuffle(tf3)[0]

<tf.Tensor: shape=(5, 2), dtype=int64, numpy=
array([[21, 22],
       [23, 24],
       [25, 26],
       [27, 28],
       [29, 30]])>

In [ ]:
rank4_tf = tf.zeros([2,3,4,5])

In [ ]:
rank4_tf.shape, rank4_tf.ndim, tf.size(rank4_tf)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
tf.size(rank4_tf).numpy()

120

# Tensor Indexing<hr>

In [ ]:
rank4_tf[:2,:2,:3,:4]

<tf.Tensor: shape=(2, 2, 3, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank4_tf

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
tf4 = tf.constant([[1,2],
                   [3,4]])
tf4

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
tf4[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [ ]:
tf5 = tf.constant(np.arange(1,121), shape = (2,3,4,5))
tf5

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int64, numpy=
array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]])>

In [ ]:
tf5[:,:,2:,3:], tf5[0,1,1:3,2:4]

(<tf.Tensor: shape=(2, 3, 2, 2), dtype=int64, numpy=
 array([[[[ 14,  15],
          [ 19,  20]],
 
         [[ 34,  35],
          [ 39,  40]],
 
         [[ 54,  55],
          [ 59,  60]]],
 
 
        [[[ 74,  75],
          [ 79,  80]],
 
         [[ 94,  95],
          [ 99, 100]],
 
         [[114, 115],
          [119, 120]]]])>, <tf.Tensor: shape=(2, 2), dtype=int64, numpy=
 array([[28, 29],
        [33, 34]])>)

In [ ]:
tf.transpose(tf5)

<tf.Tensor: shape=(5, 4, 3, 2), dtype=int64, numpy=
array([[[[  1,  61],
         [ 21,  81],
         [ 41, 101]],

        [[  6,  66],
         [ 26,  86],
         [ 46, 106]],

        [[ 11,  71],
         [ 31,  91],
         [ 51, 111]],

        [[ 16,  76],
         [ 36,  96],
         [ 56, 116]]],


       [[[  2,  62],
         [ 22,  82],
         [ 42, 102]],

        [[  7,  67],
         [ 27,  87],
         [ 47, 107]],

        [[ 12,  72],
         [ 32,  92],
         [ 52, 112]],

        [[ 17,  77],
         [ 37,  97],
         [ 57, 117]]],


       [[[  3,  63],
         [ 23,  83],
         [ 43, 103]],

        [[  8,  68],
         [ 28,  88],
         [ 48, 108]],

        [[ 13,  73],
         [ 33,  93],
         [ 53, 113]],

        [[ 18,  78],
         [ 38,  98],
         [ 58, 118]]],


       [[[  4,  64],
         [ 24,  84],
         [ 44, 104]],

        [[  9,  69],
         [ 29,  89],
         [ 49, 109]],

        [[ 14,  74],
         [ 

# Mathetical Operations <hr>

In [ ]:
tf_a = tf.constant(np.arange(1,25), shape = (6,4))
tf_b = tf.constant(np.arange(1,21), shape = (5,4))

In [ ]:
tf_a, tf_a + 10, tf_a - 10, tf_a *10, tf_a/ 10

(<tf.Tensor: shape=(6, 4), dtype=int64, numpy=
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])>, <tf.Tensor: shape=(6, 4), dtype=int64, numpy=
 array([[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22],
        [23, 24, 25, 26],
        [27, 28, 29, 30],
        [31, 32, 33, 34]])>, <tf.Tensor: shape=(6, 4), dtype=int64, numpy=
 array([[-9, -8, -7, -6],
        [-5, -4, -3, -2],
        [-1,  0,  1,  2],
        [ 3,  4,  5,  6],
        [ 7,  8,  9, 10],
        [11, 12, 13, 14]])>, <tf.Tensor: shape=(6, 4), dtype=int64, numpy=
 array([[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120],
        [130, 140, 150, 160],
        [170, 180, 190, 200],
        [210, 220, 230, 240]])>, <tf.Tensor: shape=(6, 4), dtype=float64, numpy=
 array([[0.1, 0.2, 0.3, 0.4],
        [0.5, 0.6, 0.7, 0.8],
        [0.9, 1. , 1.1, 1.2],
        [1.3, 1.4

In [ ]:
tf.matmul(tf_a, tf.reshape(tf_b, shape = (4,5)))

<tf.Tensor: shape=(6, 5), dtype=int64, numpy=
array([[ 110,  120,  130,  140,  150],
       [ 246,  272,  298,  324,  350],
       [ 382,  424,  466,  508,  550],
       [ 518,  576,  634,  692,  750],
       [ 654,  728,  802,  876,  950],
       [ 790,  880,  970, 1060, 1150]])>

In [ ]:
tf.matmul(tf_a, tf.transpose(tf_b))

<tf.Tensor: shape=(6, 5), dtype=int64, numpy=
array([[  30,   70,  110,  150,  190],
       [  70,  174,  278,  382,  486],
       [ 110,  278,  446,  614,  782],
       [ 150,  382,  614,  846, 1078],
       [ 190,  486,  782, 1078, 1374],
       [ 230,  590,  950, 1310, 1670]])>

In [ ]:
tf_n  = tf.constant(np.random.randint(1,100,50))

In [ ]:
tf.reduce_min(tf_n), tf.reduce_max(tf_n), tf.reduce_mean(tf_n)   

(<tf.Tensor: shape=(), dtype=int64, numpy=4>,
 <tf.Tensor: shape=(), dtype=int64, numpy=99>,
 <tf.Tensor: shape=(), dtype=int64, numpy=49>)

In [ ]:
tf_n, tf.argmax(tf_n), tf.argmin(tf_n), tf.argsort(tf_n)

(<tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([74, 49,  6, 34, 28, 41, 70, 49, 64, 38, 22, 56, 82, 55, 26, 97, 37,
        38, 81, 96, 44, 53, 97, 27, 39, 62, 41, 99, 12, 80, 84, 31, 11, 59,
        24, 74, 94, 85, 58, 25, 41, 94, 33, 16, 24,  4,  7, 28, 59, 36])>,
 <tf.Tensor: shape=(), dtype=int64, numpy=27>,
 <tf.Tensor: shape=(), dtype=int64, numpy=45>,
 <tf.Tensor: shape=(50,), dtype=int32, numpy=
 array([45,  2, 46, 32, 28, 43, 10, 34, 44, 39, 14, 23,  4, 47, 31, 42,  3,
        49, 16,  9, 17, 24,  5, 26, 40, 20,  1,  7, 21, 13, 11, 38, 33, 48,
        25,  8,  6,  0, 35, 29, 18, 12, 30, 37, 36, 41, 19, 15, 22, 27],
       dtype=int32)>)

In [ ]:
tf.one_hot([1,2,3,4], depth = 5, on_value="Shivam", off_value="No-Shivam")

<tf.Tensor: shape=(4, 5), dtype=string, numpy=
array([[b'No-Shivam', b'Shivam', b'No-Shivam', b'No-Shivam',
        b'No-Shivam'],
       [b'No-Shivam', b'No-Shivam', b'Shivam', b'No-Shivam',
        b'No-Shivam'],
       [b'No-Shivam', b'No-Shivam', b'No-Shivam', b'Shivam',
        b'No-Shivam'],
       [b'No-Shivam', b'No-Shivam', b'No-Shivam', b'No-Shivam',
        b'Shivam']], dtype=object)>

In [ ]:
tf6 = tf.constant(np.arange(1,11), dtype=tf.float32)
tf.square(tf6)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.],
      dtype=float32)>

In [ ]:
tf.sqrt(tf6)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        , 3.1622777 ],
      dtype=float32)>