<a href="https://colab.research.google.com/github/SP-TechForest/Python-creations/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import pandas

In [3]:
print(tf.__version__)

2.7.0


In [4]:
scalar = tf.constant(7)

# Use of COnstant and Variable to make tensors<hr>

In [5]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
scalar.ndim

0

In [9]:
vector = tf.constant([10,20])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [10]:
vector.ndim

1

In [12]:
matrix = tf.constant([[1,2]
                      ,[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [13]:
matrix.ndim

2

In [18]:
matrix2 = tf.constant([[1,2,3],[4,5,6],[6,7,8]], dtype = tf.float16)

In [19]:
matrix2

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [6., 7., 8.]], dtype=float16)>

In [25]:
tensor = tf.constant([[[1,2,3,4],
                      [5,6,7,8]],
                     [[1,2,3,4],
                      [1,2,3,4]],
                     [[1,2,3,4],
                      [1,2,3,4]]])
tensor

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]]], dtype=int32)>

In [26]:
tensor.ndim

3

In [28]:
tensor2  = tf.constant([[[1,2,3,4]],[[1,2,3,4]]])
tensor2

<tf.Tensor: shape=(2, 1, 4), dtype=int32, numpy=
array([[[1, 2, 3, 4]],

       [[1, 2, 3, 4]]], dtype=int32)>

In [34]:
t1 = tf.Variable(20)

In [37]:
changable_tensor = tf.Variable([10,10])
unchangable_tensor = tf.constant([10,10])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [43]:
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>

use assign to change value 

In [47]:
changable_tensor2 = tf.Variable([[[1,2,3,4],
                      [5,6,7,8]],
                     [[1,2,3,4],
                      [1,2,3,4]],
                     [[1,2,3,4],
                      [1,2,3,4]]])
changable_tensor2

<tf.Variable 'Variable:0' shape=(3, 2, 4) dtype=int32, numpy=
array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]]], dtype=int32)>

Constant creates unchangable tensros. <br>
Variable generates changable tensors. 

## Create random tensors<hr>

In [79]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [72]:
tf.random.set_seed(111)
tf.random.uniform([1,5,6])

<tf.Tensor: shape=(1, 5, 6), dtype=float32, numpy=
array([[[0.22793007, 0.07242179, 0.25905025, 0.26928675, 0.99596477,
         0.21952057],
        [0.19156086, 0.7613294 , 0.89160967, 0.22138035, 0.1934278 ,
         0.6977569 ],
        [0.5775132 , 0.6305827 , 0.5463754 , 0.7712686 , 0.6112319 ,
         0.00575221],
        [0.6060922 , 0.1935494 , 0.74294245, 0.980145  , 0.13235426,
         0.6069268 ],
        [0.35117865, 0.8777567 , 0.12334549, 0.2773801 , 0.517432  ,
         0.04045439]]], dtype=float32)>

In [73]:
tf.random.uniform([1,5,6])

<tf.Tensor: shape=(1, 5, 6), dtype=float32, numpy=
array([[[0.86369586, 0.60063684, 0.95674896, 0.7128948 , 0.50341344,
         0.9982449 ],
        [0.56112504, 0.37694383, 0.83077204, 0.01545227, 0.33032954,
         0.6329814 ],
        [0.7801497 , 0.8009933 , 0.9957398 , 0.5391377 , 0.45974958,
         0.23468137],
        [0.51416945, 0.9229262 , 0.52210605, 0.1595906 , 0.02170455,
         0.97483253],
        [0.13269508, 0.68724465, 0.74411213, 0.46654022, 0.607587  ,
         0.32690895]]], dtype=float32)>

In [78]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3, 2)) # create tensor from a normal distribution 
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [86]:
tf.random.set_seed(4)
a = tf.random.shuffle([1,2,3,4,5,6], seed=567436).numpy()
tf.random.set_seed(4)
b = tf.random.shuffle([1,2,3,4,5,6], seed=567436).numpy()
a,b

(array([1, 4, 2, 3, 5, 6], dtype=int32),
 array([1, 4, 2, 3, 5, 6], dtype=int32))

If we use seed then we will get same random out put, But the seed value should be same, if seed value is different then your values will be different.<br>
you must have to assign seed value before each operation. 





# Norrmal Vs. Uniform<hr>
tf.random.normal() -> Make Normal distribution of data points (not eaqualy)<br>

tf.random.uniform -> Make Uniform distribution of data points (quality)


In [93]:
tf.random.uniform([5]).ndim

1

In [98]:
tf.random.normal(shape = ([3,5])).ndim

2